name: bizcard_app
description: "A Business digital card app."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #icons
  antdesign_icons: ^0.0.3

  #image
  cached_network_image: ^3.3.1
  image_picker: ^1.0.5
  image_cropper: ^5.0.1

  #files
  path_provider: ^2.1.2
  path: ^1.8.3

  #internationalize
  intl: ^0.19.0

  #local-storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #network
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  http_parser: ^4.0.2
  uni_links: ^0.5.1
  url_launcher: ^6.2.4

  #SML
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #style
  google_fonts: ^6.1.0

  #utils
  bot_toast: ^4.1.3
  share_plus: ^7.2.1
  page_transition: ^2.1.0

  #ML
  google_ml_kit: ^0.16.3
  dart_openai: ^5.0.0

  #widgets
  animated_toggle_switch: ^0.8.2
  animated_bottom_navigation_bar: ^1.3.0
  camera: ^0.10.5+9
  carousel_slider: ^4.2.1
  dotted_border: ^2.1.0
  font_awesome_flutter: ^10.7.0
  lottie: ^3.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  pretty_qr_code: ^3.1.0
  dropdown_button2: ^2.3.9
  animated_digit: ^3.2.3
  shimmer: ^3.0.0
  open_file_plus: ^3.4.1
  animated_text_kit: ^4.2.2
  syncfusion_flutter_charts: ^24.2.3
  simple_gradient_text: ^1.3.0
  showcaseview: ^2.0.3
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "res/images/app-logo.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:

  uses-material-design: true

  assets:
    - res/images/
    - res/icons/
    - res/gifs/
    - res/lottie/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
